### ISSUE TITLE
Crear Instagram Link animado

### ISSUE THREAD

**Issue by MarcoJ18** [MarcoJ18/knowledge-hub.io#37]
Añadir este css al divi general:

https://i.imgur.com/SgdMzzZ.png

```css
    .degradado-instagram a{
      font-weight: bold;
      background: linear-gradient(270deg, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5, #feda75);
      background-size: 600% 600%;
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      display: inline-block;
      animation: moverDegradado 8s ease infinite;
    }

    @keyframes moverDegradado {
      0% {
        background-position: 0% 50%;
      }
      50% {
        background-position: 100% 50%;
      }
      100% {
        background-position: 0% 50%;
      }
    }
  
```

Se añade en divi en general y luego se pone la clase `.degrado-instagram` al elemento que lo necesite:

https://i.imgur.com/0PWtjIC.png

> [!IMPORTANT]
> Solo funciona con elementos que tengan un link o hipervinculo
> https://i.imgur.com/PwO6MaB.png
